spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://rm-bp15echqdhbnl28412o.mysql.rds.aliyuncs.com:3306/primecardhub?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: primehubcardadmin
    password: Masamiyui_1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # 保留H2控制台配置，但禁用
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: false

# 应用配置
server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: primecardHubSecretKey2024ForJWTTokenGeneration
  expiration: 86400000 # 24小时

# 文件上传配置
file:
  upload-dir: ./uploads
  max-size: 10MB
  allowed-types: image/jpeg,image/png,image/gif,application/pdf
  
# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "Authorization"
  allow-credentials: true
  max-age: 3600

# 日志配置
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.primehub.primecardadmin: DEBUG

# Springdoc OpenAPI 配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  show-actuator: false
  group-configs:
    - group: 'default'
      display-name: 'PrimeCardHub API'
      paths-to-match: '/**'